### ISSUE TITLE
Check for non markdown files in content

### ISSUE THREAD

**Issue by hofbi** [latex4ei/tex4tum#13]
The following non markdown files are in the content folder and they should be removed if they are not used or should be moved to the right place if used.
  - `physics`
    - `mechanics->motion.html`
    - `optic` `.html` + `.js`
    - `index.html`
  - `electronics->bus->idee.txt`
  - `math`
    - `geo->trigonometry.md` table is outcommented
    - `statistics->*.html`
  - `it`
    - `tools->gdb.html`
    - `language->formal_languages` file has no ending

**Comment by elgor** [comment]
all non .md files could be removed
