### ISSUE TITLE
Auto generate TOC in main files from files in layers below

### ISSUE THREAD

**Issue by hofbi** [latex4ei/tex4tum#14]
- The table of contents (including links) in the `index.md` or `<main-topic>.md` should be autogenerated from the files in the layers below.

This could be a useful solution: https://gist.github.com/danblakemore/1d11b18f475c6502d96b6474c813396b

**Comment by elgor** [comment]
Maybe we should use index.md in every folder instead of <main-topic>.md outside of the folders

**Comment by hofbi** [comment]
> instead of .md outside of the folders

Please explain this

**Comment by elgor** [comment]
Right now we have:
```
/
  electronics/
  physics/
  electronics.md
  physics.md
```

I think it would be better if we change to
```
/
  electronics/
       index.md
  physics/
       index.md
```

**Comment by elgor** [comment]
ok for the auto-generation of the TOCs it seems to be practical to have the structure like
```
/
  electronics/
       electronics.md
  physics/
       physics.md
```
because this will keep unique names (otherwise jekyll will generate only one index.html)
