### ISSUE TITLE
Content Style: Tab boxes

### ISSUE THREAD

**Issue by emareg** [latex4ei/tex4tum#20]
It should be possible to create tab boxes which is a box with several tabs, as demonstrated by:
http://www.w3schools.com/howto/howto_js_tabs.asp

It would be useful for code examples in different languages and topics with several variants. 
Compared to drop-down menus, tabs are all visible at the same time and can be selected with one click instead of two.

**Comment by hofbi** [comment]
Use bootstrap tab style for our tab boxes
