### ISSUE TITLE
Instant Answers of certain Queries

### ISSUE THREAD

**Issue by emareg** [latex4ei/tex4tum#21]
The search bar should be able to provide instant answers to certain queries. The content should be dynamically loaded into the main view without the need to hit enter.

For example if I type "c0", I probably want to know the speed of light which should be immediately displayed. Other use cases could be numbers displayed in different number systems, the possible meaning of Greek symbols, or simple calculations.

For the implementation, the search bar should distinguish between "normal article" queries and "instant queries".

**Comment by elgor** [comment]
We could also integrate a simple calculator using math.js:
http://mathjs.org/
it could solve simple calculations and even derivations

**Comment by hofbi** [comment]
This is already done right? Calculator is including `<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjs/4.4.2/math.min.js"></script>`.

As we use mathjs from CDN we should remove the math.min.js in the assets.

**Comment by hofbi** [comment]
Outdated since swicthing to mkdocs
