### ISSUE TITLE
Use mermaid fo fancy diagrams

### ISSUE THREAD

**Issue by hofbi** [latex4ei/tex4tum#23]
We could use this plugin https://github.com/knsv/mermaid for drawing fancy diagrams

**Comment by hofbi** [comment]
Mermaid is added and i also created a liquid block for that

    {% mermaid %}
    DRAWING GOES HERE
    {% endmermaid %}

Now we can create diagrams directly in the markdown files. 

@elgor Maybe we can also change some simple drawings from svg to mermaid diagrams

**Comment by elgor** [comment]
Another interesting library for function plotting:
http://maurizzzio.github.io/function-plot/

We should make an estimation how all the JS libraries will slow down the website which would violate some of our requirements and design goals

**Comment by hofbi** [comment]
I will try to include this and create a benchmark to get the "slowdownrate"

**Comment by hofbi** [comment]
Outdated since swicthing to mkdocs
