### ISSUE TITLE
Fix all Katex errors

### ISSUE THREAD

**Issue by hofbi** [latex4ei/tex4tum#25]
On some pages we get Katex parser errors. We need to check all content files and fix the errors. Most of the should be related to Latex Syntax errors. While checking all content files we should also use the same markdown style. 

Tasklist:
- [x] Fix all Katex Parser errors
- [ ] Review and convert content to [Github Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by elgor** [comment]
Some errors are caused by a an issue in pandoc: https://github.com/jgm/pandoc/issues/1390

for example \oiint\limits does not render because of the extra { }

**Comment by elgor** [comment]
I fixed most of the errors, such as unicode problems and missing tex definitions.
However the issue of \oiint\limits still remains (see integral.md)

What does "Review and convert content to Github Markdown" mean?
