### ISSUE TITLE
Fix deployment

### ISSUE THREAD

**Issue by hofbi** [latex4ei/tex4tum#35]
The gh-pages deployment build from travis contains strange latex comment at the beginning of each page. They have to be removed before we can use out deployment.

This images shows the diff between the correct build on the left and the build by travis on the right.

![grafik](https://user-images.githubusercontent.com/10724293/40873147-474c8fa4-665b-11e8-9128-d3e55f503951.png)

Once this is fixed we can remove the `docs` folder from master branch and change the sources for gh pages to gh-pages branch.

**Comment by hofbi** [comment]
Removing the comments from latex definitions still keeps some blank character and keeps the style for alignment.

@emareg Maybe this is related with some UTF-8 encoding, but setting to UTF-8 as in the readme will break the travis build.

**Comment by hofbi** [comment]
Switching the CI to docker

@emareg Currently the build fails for running in production mode which includes the hook for generating the TOC. Could you fix the TOC generator. This is the related error line

```shell
/srv/jekyll/_plugins/tex4tum_hooks.rb:273:in `partition': invalid byte sequence in US-ASCII (ArgumentError)
```

**Comment by emareg** [comment]
The error sounds like an encoding problem. I thought everything should be encoded and decoded as UTF-8. Is there something in the docker image that might read files as ASCII?

**Comment by hofbi** [comment]
Not sure. I had to change `<h1 class="text-primary">TeX4TUM – Interactive Knowledge Platform</h1>` to `<h1 class="text-primary">TeX4TUM - Interactive Knowledge Platform</h1>` which was also an encoding error. Could be that there are more.
