### ISSUE TITLE
Include bootstrap as gem

### ISSUE THREAD

**Issue by hofbi** [latex4ei/tex4tum#50]
@emareg Nice that you fixed #47. I was just thinking about how we should handle bootstrap ideally. Because updating all the sources if something changes is not the best solution. 

Do we have any modifications on the bootstrap sources? Because if not we could directly use the gem, which would also allow the github bot to check for security issues.

**Comment by emareg** [comment]
We modify some bootstrap classes in `_sass/bootstrap/_custom.scss`. 
If we include BS with gem, could it "auto-break" something with a new version? I think manual updates to certain stable releases should be fine for now but if we grow further we should of course rethink this.

**Comment by hofbi** [comment]
But in the gem file we could also specify a specific version to prevent auto-breaks. And as already mentioned this would allow the github dependency checker to inform us about security issues. So if using the gem works with out setup we should switch to this.

Independently from the style content we could remove the bootstrap.min.js in our assets and use the cdn to have less trashy files in our code.

**Comment by emareg** [comment]
Yes we could give it a try. Is it in general a good idea to rely on cdn? If we host the files ourselves and specify the hash then we can still make use of browser caching if the file was already loaded from cdn but we are not depending on their availability and responsiveness.

**Comment by hofbi** [comment]
Can you give it a try. Maybe put it on a branch so we can compare both approaches

**Comment by hofbi** [comment]
Right now, bootstrap 5 is already released, so we should think of a migration and also include it in a way that allows for simple updates in case of security issues

**Comment by hofbi** [comment]
Should be doable via gems: https://getbootstrap.com/docs/5.0/getting-started/download/#rubygems and customize with https://github.com/twbs/bootstrap-rubygem/blob/master/README.md#sass-individual-components

**Comment by hofbi** [comment]
@emareg I did a basic setup for using bootstrap as gem in https://github.com/latex4ei/tex4tum/tree/bootstrap_gem

Right now there seem to be some style issues mabe due to our modifications/customizations. I guess you know best which parts you modified.
