### ISSUE TITLE
Full responsive design

### ISSUE THREAD

**Issue by elgor** [latex4ei/tex4tum#7]
The layout should adjust to viewport width. Font size should be easily readable on desktops and smartphones. There should be a minimum width in `em` that is required to render the page. Page content should not shrink further than this minimum width.

Open design questions: 

* should tables with many columns wrap around or split or exceed the width? 
* should images shrink to fit the width? maybe click to zoom?

**Comment by hofbi** [comment]
to realize this we should choose a framework like these:
  - [Bootstrap](https://getbootstrap.com/)
  - [Material Design Lite](https://getmdl.io/)

I already tried something on both, so i would prefer bootstrap. See [this](http://tutorialzine.com/2015/07/comparing-bootstrap-with-mdl/) small comparison as reference.

**Comment by hofbi** [comment]
We will use [Bootstrap 4](https://v4-alpha.getbootstrap.com/getting-started/download/)
